using System.Collections.Generic;
using System.Linq;
using Microsoft.Maui.Controls;
using Patel8sd_ContactList.Models; // Ensure this namespace is included
using MyContact = Patel8sd_ContactList.Models.Contact; // Alias for your custom Contact model

namespace Patel8sd_ContactList;

public partial class MainPage : ContentPage
{
    // No private CollectionView contactsCollectionView; declaration needed here.
    // It's automatically generated by x:Name in MainPage.xaml.

    public List<ContactGroup> ContactGroups { get; set; }

    public MainPage()
    {
        InitializeComponent();

        var contacts = new List<MyContact> // Using MyContact for consistency
        {
            new MyContact { Name="Abram", Email="abram@mail.com", PhoneNumber="6457854788", Description="Friend", Photo="Pic1.png" },
            new MyContact { Name="Aarav", Email="aarav@mail.com", PhoneNumber="1234576767", Description="Classmate", Photo="Pic1.png" },
            new MyContact { Name="Bosco", Email="bosco@mail.com", PhoneNumber="2345672131", Description="Cousin", Photo="Pic2.png" },
            new MyContact { Name="Bharat", Email="bharat@mail.com", PhoneNumber="2345681212", Description="Sister", Photo="Pic2.png" },
            new MyContact { Name="Champ", Email="champ@mail.com", PhoneNumber="3456789523", Description="Employee", Photo="Pic3.png" },
            new MyContact { Name="Celice", Email="celice@mail.com", PhoneNumber="3456798742", Description="Colleague", Photo="Pic3.png" },
            new MyContact { Name="Dravid", Email="dravid@mail.com", PhoneNumber="4567891256", Description="Roommate", Photo="Pic4.png" },
            new MyContact { Name="David", Email="david@mail.com", PhoneNumber="4567808956", Description="Uncle", Photo="Pic4.png" },
            new MyContact { Name="Evaline", Email="evaline@mail.com", PhoneNumber="5678908642", Description="Cousin", Photo="Pic5.png" },
            new MyContact { Name="Emma", Email="emma@mail.com", PhoneNumber="5678912389", Description="Family", Photo="Pic5.png" },
            new MyContact { Name="Farah", Email="farah@mail.com", PhoneNumber="6789016532", Description="Teammate", Photo="Pic1.png" },
            new MyContact { Name="Fakru", Email="fakru@mail.com", PhoneNumber="6789028521", Description="Teammate", Photo="Pic1.png" },
            new MyContact { Name="Gaurav", Email="gaurav@mail.com", PhoneNumber="7890126975", Description="Neighbor", Photo="Pic2.png" },
            new MyContact { Name="Glenn", Email="glenn@mail.com", PhoneNumber="7890135632", Description="Doctor", Photo="Pic2.png" },
            new MyContact { Name="Hina", Email="hina@mail.com", PhoneNumber="8901237842", Description="Dentist", Photo="Pic3.png" },
        };

        ContactGroups = contacts
            .GroupBy(c => c.Name[0].ToString())
            .OrderBy(g => g.Key)
            .Select(g => new ContactGroup(g.Key, g))
            .ToList();

        // contactsCollectionView is accessible here because it's defined with x:Name in MainPage.xaml
        contactsCollectionView.ItemsSource = ContactGroups;
    }

    private async void OnContactSelected(object sender, SelectionChangedEventArgs e)
    {
        if (e.CurrentSelection.FirstOrDefault() is MyContact selectedContact) // Using MyContact here
        {
            await Navigation.PushAsync(new DetailsPage(selectedContact));
            ((CollectionView)sender).SelectedItem = null;
        }
    }
}